corrected  path

diff --git a/.github/workflows/update-release-links.yml b/.github/workflows/update-release-links.yml
--- a/.github/workflows/update-release-links.yml
+++ b/.github/workflows/update-release-links.yml
@@ -33,10 +33,15 @@ jobs:
                   done
         
                   # Replace the $SELECTION_PLACEHOLDER$ in index.html
-                  sed -i '/$SELECTION_PLACEHOLDER$/{
-                      r /dev/stdin
-                      d
-                  }' /home/jovyan/personal/skababji/projects/pysdg-releases/docs/index.html <<< "$links"
+                  if [ -f docs/index.html ]; then
+                      sed -i '/$SELECTION_PLACEHOLDER$/{
+                          r /dev/stdin
+                          d
+                      }' docs/index.html <<< "$links"
+                  else
+                      echo "Error: docs/index.html does not exist."
+                      exit 1
+                  fi
         
               - name: Commit and push changes
                 run: |
